#!/bin/bash

# Generate a random number between 1 and 100
#random_number=$(( ( RANDOM % 100 )  + 1 ))

# Generate random float between -2.5 and 2.5
min=-2.0
max=2.0

for i in {1..20}
do
r1_x=$(awk "BEGIN {print ($RANDOM * ($max - $min) / 32767) + $min}")
r1_y=$(awk "BEGIN {print ($RANDOM * ($max - $min) / 32767) + $min}")
r2_x=$(awk "BEGIN {print ($RANDOM * ($max - $min) / 32767) + $min}")
r2_y=$(awk "BEGIN {print ($RANDOM * ($max - $min) / 32767) + $min}")

echo "r1_x: $r1_x"
echo "r1_y: $r1_y"
echo "r2_x: $r2_x"
echo "r2_y: $r2_y"


roslaunch gruppe5 start.launch r1_x:=$r1_x r1_y:=$r1_y r2_x:=$r2_x r2_y:=$r2_y &

./killROS 

done
exit 0